### ISSUE TITLE
Listing repository branches doesn't work if branch names contain a /

### ISSUE THREAD

**Issue by ghost** [dustin/py-github#40]
Unfortunately this is common with branches imported from git-svn, as / is used as tree path separator there. E.g. see http://github.com/api/v2/xml/repos/show/django/django/branches , which results in

```
xml.parsers.expat.ExpatError: not well-formed (invalid token)
```

when

```
gh.repos.branches('django', 'django')
```

is run.

**Comment by dustin** [comment]
I think this might be a "use JSON" error.  Let's call it a dup of #43
